### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/keas.kmi#11]
There have not been any code changes but since some days the tests are broken, see https://github.com/zopefoundation/keas.kmi/actions/runs/1275128310

Probably one of the dependencies has changed in a way breaking the tests here.

**Comment by icemac** [comment]
@agroszer You seem to use this project – maybe you could find some time to look into this issue.

**Comment by agroszer** [comment]
@icemac yup, I'll take a look

**Comment by jordanvance** [comment]
broken by a pycryptodome change, I believe.

**Comment by jordanvance** [comment]
fixed by https://github.com/Legrandin/pycryptodome/pull/556 which is slotted for pycryptodome 3.11 (https://github.com/Legrandin/pycryptodome/blob/master/Changelog.rst)

**Comment by icemac** [comment]
So we just have to wait for the 3.11 release?

**Comment by jordanvance** [comment]
@icemac I believe so, or freeze pycryptodome at 3.0.1

**Comment by jordanvance** [comment]
new pycryptodome released. tests pass.
